#On all the worker nodes of Kubernetes , we are disabling SWAP command , disabling SELinux , installing Docker
#Starting Docker service , Ensure IPv6 Bridge Filtering is Enabled , Add Kubernetes YUM Repository . 
- hosts: all
  become: yes
  tasks:
   - name: Disable SWAP
     shell: |
       swapoff -a

   - name: Disable SWAP in fstab
     lineinfile:
       path: /etc/fstab
       regexp: 'swap'
       state: absent

   - name: disable SELinux
     command: setenforce 0
     ignore_errors: yes

   - name: install Docker
     yum:
       name: docker
       state: present
       update_cache: true

   - name: start Docker
     service:
       name: docker
       state: started
       enabled: true



   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: add Kubernetes YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes
      
#Install and Configure Kubernetes Components on Nodes:
#Installs kubelet with version 1.21.3.
#Installs kubeadm with version 1.21.3.
#Starts the kubelet service and ensures it's enabled.
#For the 'master' host, installs kubectl with version 1.21.3, allowing downgrades if necessary.

#Configure Kubernetes Nodes:
#This code block is intended to be used on the 'master' host. It includes tasks that need elevated privileges (become: yes):
#Installs kubectl with version 1.21.3, allowing downgrades if necessary.

#These code blocks together set up Kubernetes components (kubelet, kubeadm, kubectl) on nodes, ensuring that the environment is prepared for Kubernetes deployment and management.

   - name: install kubelet
     yum:
        name: kubelet-1.21.3
        state: present
        update_cache: true

   - name: install kubeadm
     yum:
        name: kubeadm-1.21.3
        state: present

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started

- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     yum:
        name: kubectl-1.21.3
        state: present
        allow_downgrade: yes
